doc-warnings: yes
test-warnings: no
strictness: high
max-line-length: 120
uses:
  - django
autodetect: yes
ignore-paths:
  - docs
  - django2_propeller_demo
ignore-patterns:
  - ^manage.py$
  - (^|/)docs(/|$)
  - ^tests.py$
python-targets:
  - 3