# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='navbar',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_propeller.NavbarItem'),
        ),
    ]
